// ─────────────────────────────────────────────────────────────────────────────
// BANCO DE PREGUNTAS CLASE C — MOTOCICLETAS
// Fuente: Libro para la Conducción en Chile (CONASET) — Sección Motocicletas
//         Cuestionario Base Examen Teórico Clase C (mejoresconductores.conaset.cl)
// ─────────────────────────────────────────────────────────────────────────────

export const PREGUNTAS_MOTO = [

  // ── CONDUCTA VIAL (moto) ────────────────────────────────────────────────────

  {
    id: 1001,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 1,
    pregunta: "¿Por qué parte de la calzada deben circular las motocicletas por norma general?",
    opciones: [
      "Por la mitad izquierda de la calzada.",
      "Por la mitad derecha de la calzada.",
      "Por el centro exacto de la calzada.",
    ],
    correcta: 1,
    explicacion: "Al igual que todo vehículo, la motocicleta debe circular por la mitad derecha de la calzada, salvo excepciones señaladas en la ley.",
  },
  {
    id: 1002,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular entre dos filas de vehículos (filtrar) en un atochamiento?",
    opciones: [
      "Sí, siempre que lo hagan a baja velocidad.",
      "Sí, si los demás vehículos están detenidos.",
      "No, está prohibido circular entre filas de vehículos.",
    ],
    correcta: 2,
    explicacion: "La ley de tránsito chilena prohíbe que las motocicletas circulen entre filas de vehículos (conocido como 'filtrar'). Deben respetar su pista como cualquier vehículo.",
  },
  {
    id: 1003,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "Al circular en una carretera de doble pista por sentido, ¿por qué pista debe circular normalmente una motocicleta?",
    opciones: [
      "Por la pista del lado izquierdo.",
      "Por la pista del lado derecho.",
      "Por cualquier pista indistintamente.",
    ],
    correcta: 1,
    explicacion: "Los vehículos que circulan a velocidad inferior a la máxima, incluidas motocicletas, deben hacerlo por la pista de la derecha, dejando libre la pista izquierda para adelantamientos.",
  },
  {
    id: 1004,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular por las ciclovías?",
    opciones: [
      "Sí, en cualquier momento.",
      "Solo si no hay ciclistas presentes.",
      "No, las ciclovías son exclusivas para ciclistas y otros vehículos no motorizados.",
    ],
    correcta: 2,
    explicacion: "Las ciclovías están destinadas exclusivamente a bicicletas y vehículos no motorizados. Las motocicletas no pueden circular por ellas.",
  },
  {
    id: 1005,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular por la berma de una carretera?",
    opciones: [
      "Sí, si el tráfico en la calzada está muy congestionado.",
      "Sí, cuando circulan lentamente por avería.",
      "No, en ningún caso.",
    ],
    correcta: 2,
    explicacion: "Ningún vehículo puede circular por la berma. Es un espacio reservado para emergencias y peatones, no para circulación de vehículos.",
  },
  {
    id: 1006,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 3,
    pregunta: "Al aproximarse a una curva hacia la izquierda en moto, ¿qué posición debe adoptar el motociclista?",
    opciones: [
      "Mantenerse bien a la derecha de la calzada.",
      "Desplazarse hacia el centro de la calzada para tener mejor visual.",
      "Acercarse a la línea central para acortar la curva.",
    ],
    correcta: 0,
    explicacion: "Al enfrentar una curva hacia la izquierda, el motociclista debe mantenerse bien a la derecha. Esto le da mejor visual y lo ubica en una posición más segura si un vehículo viene en sentido contrario invadiendo su pista.",
  },
  {
    id: 1007,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "¿Cómo debe señalizar un motociclista un viraje a la derecha, usando señas con el brazo?",
    opciones: [
      "Brazo izquierdo extendido horizontalmente.",
      "Brazo izquierdo en ángulo recto hacia arriba.",
      "Brazo izquierdo extendido hacia abajo.",
    ],
    correcta: 1,
    explicacion: "Para indicar un viraje a la derecha con el brazo izquierdo, el motociclista debe levantar el antebrazo formando un ángulo recto hacia arriba (en 'L').",
  },
  {
    id: 1008,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "¿Cómo debe señalizar un motociclista un viraje a la izquierda, usando señas con el brazo?",
    opciones: [
      "Brazo izquierdo extendido horizontalmente.",
      "Brazo izquierdo en ángulo recto hacia arriba.",
      "Brazo izquierdo extendido hacia abajo.",
    ],
    correcta: 0,
    explicacion: "Para indicar un viraje a la izquierda, el motociclista extiende el brazo izquierdo horizontalmente, paralelo al suelo.",
  },
  {
    id: 1009,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "¿Cómo debe señalizar un motociclista una reducción de velocidad, usando señas con el brazo?",
    opciones: [
      "Brazo izquierdo extendido horizontalmente.",
      "Brazo izquierdo en ángulo recto hacia arriba.",
      "Brazo izquierdo extendido hacia abajo.",
    ],
    correcta: 2,
    explicacion: "Para indicar una reducción de velocidad, el motociclista extiende el brazo izquierdo hacia abajo con la palma mirando hacia atrás.",
  },
  {
    id: 1010,
    categoria: "Conducta Vial",
    icono: "🛣️",
    dificultad: 2,
    pregunta: "¿Pueden las motocicletas circular por las autopistas urbanas?",
    opciones: [
      "Sí, siempre.",
      "Solo si circulan a una velocidad superior a 60 km/h.",
      "No, las motocicletas tienen prohibido circular por las autopistas.",
    ],
    correcta: 2,
    explicacion: "Según la legislación chilena, las motocicletas tienen prohibido circular por las autopistas, salvo que exista señalización específica que lo permita.",
  },

  // ── SEGURIDAD VIAL (moto) ───────────────────────────────────────────────────

  {
    id: 1011,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 1,
    pregunta: "¿Es obligatorio el uso de casco para el conductor de una motocicleta en Chile?",
    opciones: [
      "Sí, siempre que circule.",
      "Solo en carreteras y caminos fuera de la ciudad.",
      "No, es optativo.",
    ],
    correcta: 0,
    explicacion: "El uso de casco es obligatorio para el conductor (y pasajero si lo lleva) de una motocicleta en todo momento, tanto en la ciudad como en carretera.",
  },
  {
    id: 1012,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 1,
    puntaje: 2,
    pregunta: "¿Es obligatorio que el pasajero de una motocicleta use casco?",
    opciones: [
      "Sí, siempre.",
      "Solo si viajan en carretera.",
      "No, el casco solo es obligatorio para el conductor.",
    ],
    correcta: 0,
    explicacion: "Tanto el conductor como el pasajero de una motocicleta están obligados a usar casco homologado en todo momento. Su incumplimiento es una infracción grave.",
  },
  {
    id: 1013,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 2,
    pregunta: "¿Por qué se recomienda a los motociclistas usar ropa de colores claros o reflectantes?",
    opciones: [
      "Para identificarse como motociclistas ante las autoridades.",
      "Para ser más visibles a otros conductores y reducir el riesgo de siniestros.",
      "Porque la ley lo exige expresamente.",
    ],
    correcta: 1,
    explicacion: "Los colores claros y reflectantes aumentan la visibilidad del motociclista, especialmente de noche o con poca luz. La falta de visibilidad es una de las principales causas de siniestros con motos.",
  },
  {
    id: 1014,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 2,
    pregunta: "¿Por qué los motociclistas son considerados 'usuarios vulnerables' de la vía?",
    opciones: [
      "Porque sus vehículos son más difíciles de manejar.",
      "Porque tienen menor protección en caso de siniestro.",
      "Porque deben usar rutas especiales.",
    ],
    correcta: 1,
    explicacion: "Los motociclistas son usuarios vulnerables porque ante un siniestro no cuentan con la protección de una carrocería, airbags ni cinturón, lo que aumenta significativamente el riesgo de lesiones graves.",
  },
  {
    id: 1015,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 3,
    pregunta: "Al circular en moto junto a vehículos estacionados, ¿cuál es el principal riesgo que debe considerar el motociclista?",
    opciones: [
      "Que los vehículos estacionados arranquen sin señalizar.",
      "Que se abran puertas de vehículos estacionados repentinamente.",
      "Que los peatones crucen desde la calzada.",
    ],
    correcta: 1,
    explicacion: "El mayor riesgo al circular junto a vehículos estacionados es que se abra una puerta repentinamente ('efecto puerta'). El motociclista debe mantener una distancia lateral segura.",
  },
  {
    id: 1016,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 2,
    pregunta: "¿A qué distancia lateral mínima debe adelantar una motocicleta a un ciclista?",
    opciones: [
      "Al menos 1 metro.",
      "Al menos 1,5 metros.",
      "Al menos 0,5 metros.",
    ],
    correcta: 1,
    explicacion: "La ley de tránsito exige mantener una distancia lateral mínima de 1,5 metros al adelantar a ciclistas. Esto aplica tanto a vehículos como a motocicletas.",
  },
  {
    id: 1017,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 2,
    pregunta: "¿Cuál es uno de los factores más importantes que afecta la estabilidad de una motocicleta en curvas?",
    opciones: [
      "El color de la moto.",
      "La velocidad excesiva al ingresar a la curva.",
      "El tipo de combustible utilizado.",
    ],
    correcta: 1,
    explicacion: "Entrar a una curva a velocidad excesiva es una de las principales causas de pérdida de control de la motocicleta. Se debe reducir la velocidad antes de ingresar y acelerar suavemente al salir.",
  },
  {
    id: 1018,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 3,
    puntaje: 2,
    pregunta: "¿Cómo afecta el alcohol a la conducción de una motocicleta?",
    opciones: [
      "Mejora los reflejos y la confianza del conductor.",
      "Reduce los reflejos, altera la percepción y aumenta el riesgo de siniestros.",
      "Solo afecta si se consume en grandes cantidades.",
    ],
    correcta: 1,
    explicacion: "El alcohol disminuye los reflejos, altera la percepción del riesgo y la coordinación motora. En motocicleta, estos efectos son especialmente peligrosos por la falta de protección del vehículo.",
  },
  {
    id: 1019,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 2,
    pregunta: "¿Qué debe hacer un motociclista cuando va a circular de noche?",
    opciones: [
      "Circular a mayor velocidad para reducir el tiempo de exposición.",
      "Asegurarse de que las luces del vehículo funcionen correctamente y usar ropa reflectante.",
      "Circular solo por carreteras iluminadas.",
    ],
    correcta: 1,
    explicacion: "De noche la visibilidad es reducida. El motociclista debe verificar el funcionamiento de sus luces y usar indumentaria reflectante para ser visible a otros conductores.",
  },
  {
    id: 1020,
    categoria: "Seguridad Vial",
    icono: "⛑️",
    dificultad: 2,
    pregunta: "¿Qué sucede con la distancia de frenado de una motocicleta en pavimento mojado?",
    opciones: [
      "Disminuye porque el agua lubrica los frenos.",
      "No varía con respecto al pavimento seco.",
      "Aumenta porque hay menor adherencia entre el neumático y el pavimento.",
    ],
    correcta: 2,
    explicacion: "En pavimento mojado la adherencia disminuye considerablemente, lo que aumenta la distancia de frenado. El motociclista debe reducir la velocidad y aumentar la distancia de seguimiento.",
  },

  // ── MECÁNICA BÁSICA (moto) ──────────────────────────────────────────────────

  {
    id: 1021,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 2,
    pregunta: "¿Con qué frecuencia se recomienda revisar la presión de los neumáticos de una motocicleta?",
    opciones: [
      "Solo cuando se note que está desinflado.",
      "Regularmente, y siempre antes de un viaje largo.",
      "Una vez al año en la revisión técnica.",
    ],
    correcta: 1,
    explicacion: "La presión correcta de los neumáticos es crucial para la seguridad en moto. Debe verificarse regularmente (idealmente cada semana) y siempre antes de viajes largos.",
  },
  {
    id: 1022,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 2,
    pregunta: "¿Qué indica un neumático de motocicleta desgastado en el centro de la banda de rodadura?",
    opciones: [
      "Que el neumático está inflado en exceso.",
      "Que el neumático tiene falta de presión.",
      "Que el neumático está inflado correctamente.",
    ],
    correcta: 0,
    explicacion: "Un neumático desgastado en el centro indica que ha estado inflado con exceso de presión. Esto reduce el área de contacto y afecta la adherencia y la estabilidad de la moto.",
  },
  {
    id: 1023,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 2,
    pregunta: "¿Qué indica un neumático de motocicleta desgastado en los bordes de la banda de rodadura?",
    opciones: [
      "Que el neumático está inflado en exceso.",
      "Que el neumático tiene falta de presión.",
      "Que la moto fue usada principalmente en curvas.",
    ],
    correcta: 1,
    explicacion: "Un neumático desgastado en los bordes (laterales) indica que circuló con presión insuficiente. La parte central no toca bien el suelo, cargando el desgaste en los bordes.",
  },
  {
    id: 1024,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 2,
    pregunta: "¿Qué función cumplen los amortiguadores de una motocicleta?",
    opciones: [
      "Mejorar el rendimiento del motor.",
      "Absorber los impactos y mantener el contacto de los neumáticos con el suelo.",
      "Reducir el consumo de combustible.",
    ],
    correcta: 1,
    explicacion: "Los amortiguadores absorben los golpes e impactos del camino, manteniendo el neumático en contacto con el suelo. Amortiguadores en mal estado reducen el control y la estabilidad.",
  },
  {
    id: 1025,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 2,
    pregunta: "¿Qué debe revisar el motociclista antes de iniciar la marcha?",
    opciones: [
      "Solo el nivel de combustible.",
      "Frenos, neumáticos, luces, nivel de aceite y combustible.",
      "Solo el estado de los neumáticos.",
    ],
    correcta: 1,
    explicacion: "Antes de salir, el motociclista debe hacer una revisión completa: frenos, estado y presión de neumáticos, funcionamiento de luces, nivel de aceite y combustible. Se llama revisión previa al viaje.",
  },
  {
    id: 1026,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 3,
    pregunta: "Si la motocicleta comienza a vibrar anormalmente en el manubrio durante la marcha, ¿qué podría indicar?",
    opciones: [
      "Que el motor está funcionando correctamente.",
      "Posible problema en los neumáticos, ruedas o sistema de dirección.",
      "Que la velocidad es demasiado baja.",
    ],
    correcta: 1,
    explicacion: "Una vibración anormal en el manubrio puede indicar problemas en los neumáticos (presión, desgaste), desequilibrio en las ruedas o fallas en la dirección. Se debe detener el vehículo y revisarlo.",
  },
  {
    id: 1027,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 2,
    pregunta: "¿Por qué es importante que la cadena de transmisión de la moto esté correctamente tensada y lubricada?",
    opciones: [
      "Para mejorar la estética de la moto.",
      "Para una transmisión eficiente de potencia y evitar roturas que podrían causar siniestros.",
      "Solo para reducir el ruido del motor.",
    ],
    correcta: 1,
    explicacion: "Una cadena mal tensada o sin lubricación puede romperse en marcha, lo que puede causar la pérdida del control de la moto. Debe revisarse periódicamente.",
  },
  {
    id: 1028,
    categoria: "Mecánica Básica",
    icono: "🔧",
    dificultad: 2,
    pregunta: "¿Qué debe hacer el motociclista si nota que los frenos responden con poca eficacia?",
    opciones: [
      "Reducir la velocidad y continuar hasta el destino.",
      "Detenerse de forma segura y revisar o reparar los frenos antes de continuar.",
      "Frenar más fuerte para compensar.",
    ],
    correcta: 1,
    explicacion: "Los frenos son el sistema de seguridad más crítico de la moto. Si no responden correctamente, se debe detener de forma segura de inmediato y no continuar hasta solucionar el problema.",
  },

  // ── REGLAMENTACIÓN (moto) ───────────────────────────────────────────────────

  {
    id: 1029,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 1,
    pregunta: "¿Desde qué edad se puede obtener la licencia de conducir Clase C (motocicleta) en Chile?",
    opciones: [
      "16 años.",
      "17 años.",
      "18 años.",
    ],
    correcta: 2,
    explicacion: "En Chile, la licencia de conducir Clase C para motocicletas se puede obtener a partir de los 18 años, al igual que la Clase B para automóviles.",
  },
  {
    id: 1030,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 1,
    pregunta: "¿Qué autoriza la licencia de conducir Clase C en Chile?",
    opciones: [
      "Conducir automóviles de hasta 9 asientos.",
      "Conducir vehículos motorizados de 2 o 3 ruedas, como motocicletas y motonetas.",
      "Conducir cualquier tipo de vehículo motorizado.",
    ],
    correcta: 1,
    explicacion: "La licencia Clase C autoriza la conducción de vehículos motorizados de dos o tres ruedas, incluyendo motocicletas, motonetas y scooters.",
  },
  {
    id: 1031,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "¿Cuántos pasajeros puede transportar una motocicleta además del conductor?",
    opciones: [
      "Dos pasajeros, si la moto tiene asiento trasero.",
      "Un pasajero, si el vehículo está diseñado para ello y el conductor tiene licencia vigente.",
      "Ninguno, las motocicletas solo permiten al conductor.",
    ],
    correcta: 1,
    explicacion: "Una motocicleta puede transportar un pasajero además del conductor, siempre que el vehículo esté equipado con asiento y reposapiés para el acompañante, y el conductor tenga licencia válida.",
  },
  {
    id: 1032,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "¿Qué documentos debe portar obligatoriamente el conductor de una motocicleta?",
    opciones: [
      "Solo la licencia de conducir.",
      "Licencia de conducir, permiso de circulación, revisión técnica y SOAP.",
      "Solo el permiso de circulación y el SOAP.",
    ],
    correcta: 1,
    explicacion: "El conductor debe portar su licencia de conducir vigente, y el vehículo debe tener permiso de circulación al día, revisión técnica vigente y SOAP (Seguro Obligatorio de Accidentes Personales).",
  },
  {
    id: 1033,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "¿Cuál es la velocidad máxima permitida para motocicletas en zonas urbanas en Chile?",
    opciones: [
      "60 km/h.",
      "50 km/h.",
      "80 km/h.",
    ],
    correcta: 1,
    explicacion: "La velocidad máxima en zonas urbanas es de 50 km/h para todos los vehículos, incluidas las motocicletas, salvo señalización específica que indique otra velocidad.",
  },
  {
    id: 1034,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "¿Cuál es la velocidad máxima permitida para motocicletas en carreteras fuera de zona urbana?",
    opciones: [
      "100 km/h.",
      "120 km/h.",
      "La misma que para automóviles según la señalización.",
    ],
    correcta: 2,
    explicacion: "Las motocicletas deben respetar los mismos límites de velocidad indicados por la señalización de cada vía. No existe un límite diferente para motos respecto a los automóviles en carreteras.",
  },
  {
    id: 1035,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "Conducir una motocicleta bajo la influencia del alcohol con una concentración de 0,5 g/L o más en la sangre se considera:",
    opciones: [
      "Una infracción leve.",
      "Una infracción grave.",
      "Una infracción gravísima.",
    ],
    correcta: 2,
    explicacion: "Conducir bajo la influencia del alcohol (0,3 a 0,79 g/L) es infracción gravísima en moto. El estado de ebriedad (0,8 g/L o más) es además un delito penal.",
  },
  {
    id: 1036,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "¿Qué ocurre si el conductor de una motocicleta es sorprendido sin casco?",
    opciones: [
      "Se le aplica una multa leve.",
      "Se le aplica una multa grave.",
      "Solo se le hace una advertencia.",
    ],
    correcta: 1,
    explicacion: "Conducir sin casco es una infracción grave, sancionada con multa. El casco es un elemento de seguridad obligatorio para motociclistas y sus pasajeros.",
  },
  {
    id: 1037,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "¿Está permitido que una motocicleta lleve carga en la zona trasera?",
    opciones: [
      "Sí, siempre que no supere el ancho del vehículo y no ponga en riesgo la estabilidad.",
      "No, las motocicletas no pueden llevar carga.",
      "Sí, sin ninguna restricción de peso.",
    ],
    correcta: 0,
    explicacion: "Las motocicletas pueden transportar carga en la zona trasera, pero esta no debe superar el ancho del vehículo ni comprometer la estabilidad o visibilidad del conductor.",
  },
  {
    id: 1038,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 3,
    puntaje: 2,
    pregunta: "Un motociclista que no respeta una luz roja de semáforo comete una infracción:",
    opciones: [
      "Leve.",
      "Grave.",
      "Gravísima.",
    ],
    correcta: 2,
    explicacion: "No detenerse ante una luz roja de semáforo es una infracción gravísima para todo conductor, incluidos los motociclistas. Puede implicar suspensión de la licencia.",
  },
  {
    id: 1039,
    categoria: "Reglamentación",
    icono: "📋",
    dificultad: 2,
    pregunta: "¿Puede una motocicleta circular con las luces apagadas de día?",
    opciones: [
      "Sí, las luces son obligatorias solo de noche.",
      "No, las motocicletas deben circular siempre con las luces encendidas, incluso de día.",
      "Solo deben encender las luces en túneles.",
    ],
    correcta: 1,
    explicacion: "En Chile, las motocicletas deben circular con las luces encendidas en todo momento, incluso de día. Esto aumenta su visibilidad frente a otros conductores.",
  },

  // ── EL INDIVIDUO EN EL TRÁNSITO ─────────────────────────────────────────────

  {
    id: 1040,
    categoria: "El Individuo en el Tránsito",
    icono: "🧠",
    dificultad: 2,
    pregunta: "¿Qué efecto tiene el cansancio en la conducción de una motocicleta?",
    opciones: [
      "No tiene efecto significativo si el conductor tiene experiencia.",
      "Disminuye los tiempos de reacción y aumenta el riesgo de error.",
      "Mejora la concentración porque el conductor se esfuerza más.",
    ],
    correcta: 1,
    explicacion: "El cansancio reduce los tiempos de reacción, disminuye la atención y aumenta la probabilidad de cometer errores de conducción. En moto, sus consecuencias son más graves.",
  },
  {
    id: 1041,
    categoria: "El Individuo en el Tránsito",
    icono: "🧠",
    dificultad: 2,
    pregunta: "¿Cómo influye el estrés en la conducción de una motocicleta?",
    opciones: [
      "Mejora la concentración y el rendimiento.",
      "No tiene efecto en conductores experimentados.",
      "Puede provocar reacciones desproporcionadas y reducir la capacidad de atención.",
    ],
    correcta: 2,
    explicacion: "Un conductor estresado puede reaccionar de manera desproporcionada ante situaciones de tránsito y tener su campo de atención reducido, lo que aumenta el riesgo de siniestros.",
  },
  {
    id: 1042,
    categoria: "El Individuo en el Tránsito",
    icono: "🧠",
    dificultad: 2,
    pregunta: "Un motociclista que conduce con exceso de confianza en sus habilidades tiende a:",
    opciones: [
      "Conducir de manera más segura por su experiencia.",
      "Tomar riesgos innecesarios y conducir a velocidades excesivas.",
      "Ser más cuidadoso con los demás usuarios de la vía.",
    ],
    correcta: 1,
    explicacion: "El exceso de confianza o la sobreestimación de las propias habilidades lleva a conducir con mayor velocidad, menor distancia de seguridad y menor atención, aumentando el riesgo.",
  },
  {
    id: 1043,
    categoria: "El Individuo en el Tránsito",
    icono: "🧠",
    dificultad: 2,
    pregunta: "¿Qué debe hacer un motociclista si siente que está muy cansado para conducir con seguridad?",
    opciones: [
      "Bajar un poco la velocidad y continuar.",
      "Tomar café para mantenerse despierto y continuar.",
      "Detenerse en un lugar seguro, descansar y reanudar la marcha solo cuando esté descansado.",
    ],
    correcta: 2,
    explicacion: "Ante el cansancio, la única solución segura es detenerse y descansar. El café u otras bebidas estimulantes no eliminan los efectos del cansancio en la conducción.",
  },
  {
    id: 1044,
    categoria: "El Individuo en el Tránsito",
    icono: "🧠",
    dificultad: 2,
    pregunta: "¿Puede un medicamento de venta libre afectar la conducción de una motocicleta?",
    opciones: [
      "No, solo los medicamentos recetados pueden afectarla.",
      "Sí, algunos medicamentos de venta libre pueden causar somnolencia u otros efectos que alteran la conducción.",
      "Solo si se mezclan con alcohol.",
    ],
    correcta: 1,
    explicacion: "Muchos medicamentos de venta libre, como antihistamínicos o analgésicos, pueden causar somnolencia o alterar los reflejos. Se debe leer el prospecto y consultar al farmacéutico.",
  },

  // ── NORMAS DE CIRCULACIÓN (moto) ────────────────────────────────────────────

  {
    id: 1045,
    categoria: "Normas de Circulación",
    icono: "🚦",
    dificultad: 2,
    pregunta: "Al circular en moto detrás de otro vehículo, ¿qué distancia de seguimiento debe mantener?",
    opciones: [
      "La misma que un automóvil, una distancia razonable y prudente.",
      "5 metros como máximo.",
      "Puede circular muy cerca porque la moto frena mejor.",
    ],
    correcta: 0,
    explicacion: "Las motocicletas deben mantener una distancia de seguimiento razonable y prudente, igual que los automóviles. Aunque frenan bien, en mojado la distancia aumenta significativamente.",
  },
  {
    id: 1046,
    categoria: "Normas de Circulación",
    icono: "🚦",
    dificultad: 2,
    pregunta: "¿Con cuánta anticipación debe señalizar un motociclista antes de realizar un viraje?",
    opciones: [
      "Con 30 metros de anticipación.",
      "Con 20 metros de anticipación.",
      "Con 10 metros de anticipación.",
    ],
    correcta: 0,
    explicacion: "La ley de tránsito exige señalizar cualquier maniobra de viraje o cambio de pista con al menos 30 metros de anticipación, utilizando indicadores de dirección o señas con el brazo.",
  },
  {
    id: 1047,
    categoria: "Normas de Circulación",
    icono: "🚦",
    dificultad: 2,
    pregunta: "¿Por qué lado debe adelantar una motocicleta a otro vehículo?",
    opciones: [
      "Por la derecha.",
      "Por la izquierda.",
      "Por cualquier lado si hay espacio suficiente.",
    ],
    correcta: 1,
    explicacion: "Los adelantamientos siempre deben realizarse por la izquierda, salvo en excepciones expresamente señaladas (como vías con pistas exclusivas). Esto aplica a todos los vehículos, incluidas las motos.",
  },
  {
    id: 1048,
    categoria: "Normas de Circulación",
    icono: "🚦",
    dificultad: 3,
    pregunta: "Al ingresar a una rotonda en moto, ¿a quién debe ceder el paso?",
    opciones: [
      "A los vehículos que ingresan desde la derecha.",
      "A los vehículos que ya circulan dentro de la rotonda.",
      "No debe ceder el paso a nadie.",
    ],
    correcta: 1,
    explicacion: "Al ingresar a una rotonda, siempre se debe ceder el paso a los vehículos que ya están circulando dentro de ella. La motocicleta no tiene ningún privilegio especial.",
  },
  {
    id: 1049,
    categoria: "Normas de Circulación",
    icono: "🚦",
    dificultad: 2,
    pregunta: "¿Qué debe hacer un motociclista al llegar a un cruce no señalizado donde se enfrentan dos vehículos?",
    opciones: [
      "Acelerar para pasar primero.",
      "Ceder el paso al vehículo que viene desde la derecha.",
      "Ceder el paso al vehículo más grande.",
    ],
    correcta: 1,
    explicacion: "En cruces sin señalización ni semáforo, se aplica la norma de la derecha: se debe ceder el paso al vehículo que viene por la derecha. Esto aplica igualmente a las motocicletas.",
  },
  {
    id: 1050,
    categoria: "Normas de Circulación",
    icono: "🚦",
    dificultad: 2,
    pregunta: "¿Puede un motociclista estacionar su moto sobre la vereda (acera)?",
    opciones: [
      "Sí, si no obstruye el paso de los peatones.",
      "No, está prohibido estacionar vehículos en la acera.",
      "Sí, las motos pueden estacionarse en la acera porque son pequeñas.",
    ],
    correcta: 1,
    explicacion: "Ningún vehículo puede estacionarse en la acera. Esto obstruye el paso de peatones, incluidas personas con movilidad reducida, y está expresamente prohibido.",
  },
  {
    id: 1051,
    categoria: "Normas de Circulación",
    icono: "🚦",
    dificultad: 3,
    pregunta: "¿Qué debe hacer un motociclista si en una intersección el semáforo está en rojo y un Carabinero le indica que avance?",
    opciones: [
      "Obedecer el semáforo y esperar el verde.",
      "Obedecer la instrucción del Carabinero.",
      "Esperar a que otros vehículos avancen primero.",
    ],
    correcta: 1,
    explicacion: "Las instrucciones del personal de Carabineros tienen preferencia sobre las señales de tránsito, incluidos los semáforos. Si un Carabinero indica avanzar, se debe obedecer.",
  },

  // ── CONVIVENCIA VIAL ────────────────────────────────────────────────────────

  {
    id: 1052,
    categoria: "Convivencia Vial",
    icono: "🤝",
    dificultad: 2,
    pregunta: "¿Por qué es importante que los motociclistas respeten especialmente el espacio de los ciclistas?",
    opciones: [
      "Porque los ciclistas tienen prioridad absoluta en toda la vía.",
      "Porque los ciclistas son usuarios vulnerables con menor protección ante un siniestro.",
      "Porque la ley lo exige solo en zonas urbanas.",
    ],
    correcta: 1,
    explicacion: "Los ciclistas, al igual que los peatones, son usuarios vulnerables. Ante un siniestro con una moto, la diferencia de masa y velocidad puede causarles lesiones graves.",
  },
  {
    id: 1053,
    categoria: "Convivencia Vial",
    icono: "🤝",
    dificultad: 2,
    pregunta: "Al acercarse a un paso de cebra donde hay un peatón esperando cruzar, ¿qué debe hacer el motociclista?",
    opciones: [
      "Acelerar para cruzar antes que el peatón empiece.",
      "Ceder el paso al peatón y esperar a que cruce.",
      "Tocar la bocina para avisar al peatón.",
    ],
    correcta: 1,
    explicacion: "El conductor debe ceder el paso a los peatones en los pasos de cebra. Esto aplica tanto si el peatón está cruzando como si está esperando para cruzar.",
  },
  {
    id: 1054,
    categoria: "Convivencia Vial",
    icono: "🤝",
    dificultad: 2,
    pregunta: "¿Cuándo puede el conductor de una motocicleta usar la bocina?",
    opciones: [
      "Para hacer notar su presencia a un amigo.",
      "Para apurar al vehículo que va delante.",
      "Solo para prevenir la ocurrencia de un siniestro.",
    ],
    correcta: 2,
    explicacion: "La bocina solo debe usarse para prevenir un siniestro. Usarla para apurar a otros conductores o llamar la atención de personas es una infracción.",
  },
  {
    id: 1055,
    categoria: "Convivencia Vial",
    icono: "🤝",
    dificultad: 2,
    pregunta: "Si el motociclista está involucrado en un siniestro con personas lesionadas, ¿qué debe hacer?",
    opciones: [
      "Continuar si el accidente fue culpa de otro.",
      "Detenerse, prestar ayuda y avisar a Carabineros de inmediato.",
      "Llamar a Carabineros desde el lugar pero no es necesario detenerse.",
    ],
    correcta: 1,
    explicacion: "Ante un siniestro con lesionados, el conductor está obligado a detenerse, prestar la ayuda posible e informar inmediatamente a Carabineros. Abandonar el lugar es un delito.",
  },

  // ── CONDUCCIÓN EFICIENTE ────────────────────────────────────────────────────

  {
    id: 1056,
    categoria: "Conducción Eficiente",
    icono: "⛽",
    dificultad: 2,
    pregunta: "¿Qué técnica de conducción permite reducir el consumo de combustible en una motocicleta?",
    opciones: [
      "Acelerar fuertemente y frenar con frecuencia.",
      "Anticipar el tráfico, mantener velocidad constante y evitar aceleraciones bruscas.",
      "Circular siempre en la marcha más baja.",
    ],
    correcta: 1,
    explicacion: "Una conducción suave y anticipativa, manteniendo velocidad constante y usando adecuadamente las marchas, reduce significativamente el consumo de combustible y el desgaste del vehículo.",
  },
  {
    id: 1057,
    categoria: "Conducción Eficiente",
    icono: "⛽",
    dificultad: 2,
    pregunta: "¿Por qué es importante el mantenimiento preventivo de la motocicleta?",
    opciones: [
      "Solo para cumplir con la revisión técnica.",
      "Para garantizar la seguridad, prolongar la vida útil del vehículo y reducir el consumo.",
      "Solo para mejorar la estética.",
    ],
    correcta: 1,
    explicacion: "El mantenimiento preventivo regular asegura que todos los sistemas de la moto funcionen correctamente, lo que es fundamental para la seguridad, la eficiencia y la durabilidad del vehículo.",
  },
];

/**
 * Genera un examen aleatorio para Clase C (moto)
 * Respeta la misma lógica de puntaje doble que Clase B
 */
export function generarExamenMoto(cantidad = 35) {
  const shuffle = (arr) => {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };

  const dobles = shuffle(PREGUNTAS_MOTO.filter((p) => p.puntaje === 2));
  const simples = shuffle(PREGUNTAS_MOTO.filter((p) => p.puntaje !== 2));

  const selDobles = dobles.slice(0, Math.min(3, dobles.length));
  const selSimples = simples.slice(0, cantidad - selDobles.length);

  return shuffle([...selDobles, ...selSimples]);
}
